# Generated by Django 4.2.30 on 2026-06-15 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RevenueAgg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('clinic', models.CharField(max_length=100)),
                ('doctor', models.CharField(max_length=100)),
                ('service', models.CharField(max_length=100)),
                ('revenue_kopecks', models.BigIntegerField(default=0)),
            ],
            options={
                'unique_together': {('date', 'clinic', 'doctor', 'service')},
            },
        ),
        migrations.CreateModel(
            name='PatientFlowAgg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('clinic', models.CharField(max_length=100)),
                ('source', models.CharField(max_length=100)),
                ('new_patients', models.IntegerField(default=0)),
                ('active_patients', models.IntegerField(default=0)),
            ],
            options={
                'unique_together': {('date', 'clinic', 'source')},
            },
        ),
        migrations.CreateModel(
            name='AppointmentDailyAgg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('clinic', models.CharField(max_length=100)),
                ('doctor', models.CharField(max_length=100)),
                ('service', models.CharField(max_length=100)),
                ('total_appointments', models.IntegerField(default=0)),
                ('completed_appointments', models.IntegerField(default=0)),
                ('cancelled_appointments', models.IntegerField(default=0)),
                ('no_show_appointments', models.IntegerField(default=0)),
            ],
            options={
                'unique_together': {('date', 'clinic', 'doctor', 'service')},
            },
        ),
    ]
